### ISSUE TITLE
Lost a line  between last tabItem and  it's pre-position tabItem

### ISSUE THREAD

**Issue by roselind** [Bob1993/react-native-segment-tab#1]
![ad41cc86-ac79-421b-9387-059dae56e0f5](https://cloud.githubusercontent.com/assets/9067932/20473962/dda6090e-affe-11e6-9e91-a85aaa3bf754.png)
Lost a line between last tabItem and it's pre-position tabItem(iOS)

**Comment by poberwong** [comment]
Thanks for your feedback. I will fix it after work....

**Comment by poberwong** [comment]
Could you please show me your code ? Because the problem didn't happen again in my demo.

The following versions is mine:
* react-native: 0.37.0
* react: 15.3.1
Look forward to hearing from you!
